theme = 'ananke'
defaultContentLanguage = 'he'
baseURL = 'https://wiseplate.blog/'
title = 'בריא וחכם'

[params]
  mainSections = ['food','compare','run']
  favicon = "/images/favicon.png"
  custom_css = ['custom.css']
  post_content_classes= "sans-serif"
  description = "יתרונות וחסרונות תזונתיים של מזונות שונים - מידע מבוסס מחקר מדעי לתזונה בריאה"
  keywords = ["תזונה", "בריאות", "ערכים תזונתיים", "יתרונות בריאותיים", "מזון בריא", "דיאטה", "פירות", "ירקות", "חלבון", "ויטמינים"]
  [params.ananke]
    show_recent_posts = true

[languages]
  [languages.he]
    languageCode = 'he'
    languageDirection = 'rtl'
    languageName = 'עברית'
    weight = 1


[[menu.main]]
  name = "רשימת מאכלים"
  url = "/food/"
[[menu.main]]
  name = "השוואה"
  url = "/compare/"
[[menu.main]]
  name = "ציוד ריצה"
  url = "/run/"